export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";
export const FETCH_ORDERS_BY_TYPE_REQUEST = "FETCH_ORDERS_BY_TYPE_REQUEST";
export const FETCH_ORDERS_BY_TYPE_SUCCESS = "FETCH_ORDERS_BY_TYPE_SUCCESS";
export const FETCH_ORDERS_BY_TYPE_FAILURE = "FETCH_ORDERS_BY_TYPE_FAILURE";
